.section .text
.global exception_handler
exception_handler:
    call serial_print_registers
    pushl $message_hlt
    call serial_printf
    addl $4, %esp
    cli
    hlt

.global exception_handler
exception_handler_term:
    call serial_print_registers
    pushl $keyboard_msg
    call terminal_writestring
    addl $4, %esp
    cli
    hlt

.macro isr_err_stub num
.global isr_stub_\num
isr_stub_\num:
    pushl $\num
    pushl $err_msg
    call serial_printf
    call exception_handler
    addl $8, %esp
    iret
.endm

.macro isr_keyboard_stub num
.global isr_stub_\num
isr_stub_\num:
    pushl $\num
    pushl $err_msg
    call serial_printf
    call exception_handler_term
    addl $8, %esp
    iret
.endm

.macro isr_no_err_stub num
.global isr_stub_\num
isr_stub_\num:
    pushl $\num
    pushl $no_err_msg
    call serial_printf
    call exception_handler
    addl $8, %esp
    iret
.endm

isr_no_err_stub 0
isr_no_err_stub 1
isr_no_err_stub 2
isr_no_err_stub 3
isr_no_err_stub 4
isr_no_err_stub 5
isr_no_err_stub 6
isr_no_err_stub 7
isr_err_stub    8
isr_no_err_stub 9
isr_err_stub    10
isr_err_stub    11
isr_err_stub    12
isr_err_stub    13
isr_err_stub    14
isr_no_err_stub 15
isr_no_err_stub 16
isr_err_stub    17
isr_no_err_stub 18
isr_no_err_stub 19
isr_no_err_stub 20
isr_no_err_stub 21
isr_no_err_stub 22
isr_no_err_stub 23
isr_no_err_stub 24
isr_no_err_stub 25
isr_no_err_stub 26
isr_no_err_stub 27
isr_no_err_stub 28
isr_no_err_stub 29
isr_err_stub    30
isr_no_err_stub 31

# irqs remaped
isr_no_err_stub 32
isr_keyboard_stub 33
isr_no_err_stub 34
isr_no_err_stub 35
isr_no_err_stub 36
isr_no_err_stub 37
isr_no_err_stub 38
isr_no_err_stub 39
isr_no_err_stub 40
isr_no_err_stub 41
isr_no_err_stub 42
isr_no_err_stub 43
isr_no_err_stub 44
isr_no_err_stub 45
isr_no_err_stub 46
isr_no_err_stub 47

.global isr_stub_table
isr_stub_table:
    .long   isr_stub_0
    .long   isr_stub_1
    .long   isr_stub_2
    .long   isr_stub_3
    .long   isr_stub_4
    .long   isr_stub_5
    .long   isr_stub_6
    .long   isr_stub_7
    .long   isr_stub_8
    .long   isr_stub_9
    .long   isr_stub_10
    .long   isr_stub_11
    .long   isr_stub_12
    .long   isr_stub_13
    .long   isr_stub_14
    .long   isr_stub_15
    .long   isr_stub_16
    .long   isr_stub_17
    .long   isr_stub_18
    .long   isr_stub_19
    .long   isr_stub_20
    .long   isr_stub_21
    .long   isr_stub_22
    .long   isr_stub_23
    .long   isr_stub_24
    .long   isr_stub_25
    .long   isr_stub_26
    .long   isr_stub_27
    .long   isr_stub_28
    .long   isr_stub_29
    .long   isr_stub_30
    .long   isr_stub_31
    .long   isr_stub_32
    .long   isr_stub_33
    .long   isr_stub_34
    .long   isr_stub_35
    .long   isr_stub_36
    .long   isr_stub_37
    .long   isr_stub_38
    .long   isr_stub_39
    .long   isr_stub_40
    .long   isr_stub_41
    .long   isr_stub_42
    .long   isr_stub_43
    .long   isr_stub_44
    .long   isr_stub_45
    .long   isr_stub_46
    .long   isr_stub_47

.section .data
err_msg:
    .ascii "EXCEPTION %d\ncode: 0x%X\n\0"
no_err_msg:
    .ascii "EXCEPTION %d\n\0"
message_hlt:
    .ascii "hlt\n\0"
keyboard_msg:
    .ascii "keyboard i\0"
